export const colorThemes = {
  blue: {
    primary: "from-blue-500 to-blue-600",
    secondary: "from-blue-400 to-blue-500",
    accent: "from-blue-600 to-blue-700",
    background: "bg-blue-50",
    text: "text-blue-900",
    card: "bg-white",
    hover: "hover:bg-blue-100",
  },
  purple: {
    primary: "from-purple-500 to-purple-600",
    secondary: "from-purple-400 to-purple-500",
    accent: "from-purple-600 to-purple-700",
    background: "bg-purple-50",
    text: "text-purple-900",
    card: "bg-white",
    hover: "hover:bg-purple-100",
  },
  green: {
    primary: "from-green-500 to-green-600",
    secondary: "from-green-400 to-green-500",
    accent: "from-green-600 to-green-700",
    background: "bg-green-50",
    text: "text-green-900",
    card: "bg-white",
    hover: "hover:bg-green-100",
  },
  orange: {
    primary: "from-orange-500 to-orange-600",
    secondary: "from-orange-400 to-orange-500",
    accent: "from-orange-600 to-orange-700",
    background: "bg-orange-50",
    text: "text-orange-900",
    card: "bg-white",
    hover: "hover:bg-orange-100",
  },
  pink: {
    primary: "from-pink-500 to-pink-600",
    secondary: "from-pink-400 to-pink-500",
    accent: "from-pink-600 to-pink-700",
    background: "bg-pink-50",
    text: "text-pink-900",
    card: "bg-white",
    hover: "hover:bg-pink-100",
  },
  dark: {
    primary: "from-gray-700 to-gray-800",
    secondary: "from-gray-600 to-gray-700",
    accent: "from-gray-800 to-gray-900",
    background: "bg-gray-900",
    text: "text-gray-100",
    card: "bg-gray-800",
    hover: "hover:bg-gray-700",
  },
  light: {
    primary: "from-gray-100 to-gray-200",
    secondary: "from-gray-50 to-gray-100",
    accent: "from-gray-200 to-gray-300",
    background: "bg-white",
    text: "text-gray-900",
    card: "bg-gray-50",
    hover: "hover:bg-gray-100",
  },
  gradient: {
    primary: "from-purple-500 via-pink-500 to-red-500",
    secondary: "from-blue-500 via-purple-500 to-pink-500",
    accent: "from-green-500 via-blue-500 to-purple-500",
    background: "bg-gradient-to-br from-purple-900 via-blue-900 to-teal-800",
    text: "text-white",
    card: "bg-white/10 backdrop-blur-lg",
    hover: "hover:bg-white/20",
  },
  creative: {
    primary: "from-purple-500 to-pink-500",
    secondary: "from-pink-500 to-red-500",
    accent: "from-red-500 to-orange-500",
    background: "bg-[#0f172a]",
    text: "text-white",
    card: "bg-gray-800",
    hover: "hover:bg-gray-700",
  },
  professional: {
    primary: "from-blue-600 to-blue-700",
    secondary: "from-gray-600 to-gray-700",
    accent: "from-gray-700 to-gray-800",
    background: "bg-gray-50",
    text: "text-gray-900",
    card: "bg-white",
    hover: "hover:bg-gray-100",
  },
}

export const fontStyles = {
  modern: {
    heading: "font-sans font-bold",
    body: "font-sans",
    accent: "font-sans font-medium",
  },
  classic: {
    heading: "font-serif font-bold",
    body: "font-serif",
    accent: "font-serif font-medium",
  },
  minimal: {
    heading: "font-sans font-light",
    body: "font-sans font-light",
    accent: "font-sans font-normal",
  },
  creative: {
    heading: "font-display font-bold",
    body: "font-sans",
    accent: "font-display font-medium",
  },
  elegant: {
    heading: "font-serif font-bold tracking-wide",
    body: "font-serif",
    accent: "font-serif font-medium",
  },
  bold: {
    heading: "font-sans font-black",
    body: "font-sans font-medium",
    accent: "font-sans font-bold",
  },
  playful: {
    heading: "font-display font-bold",
    body: "font-sans",
    accent: "font-display font-medium",
  },
  tech: {
    heading: "font-mono font-bold",
    body: "font-sans",
    accent: "font-mono font-medium",
  },
} 